### ISSUE TITLE
`env`: load from command stdout

### ISSUE THREAD

**Issue by leroyguillaume** [leroyguillaume/projectctl#33]
Handle command stdout as result of variable.

Example:
```yaml
env:
  MY_VAR:
    run: echo value
```
Expected result:
```
$ projectctl env
export MY_VAR=value
```
