### ISSUE TITLE
`use`: handle custom binary

### ISSUE THREAD

**Issue by leroyguillaume** [leroyguillaume/projectctl#36]
Handle custom binary in `use` configuration entry.

Example:
```yaml
use:
  my-software:
    version: 1.2.3
    binary-url: https://my-software.com/{{ version }}/my-software-{{ version }}-{{ os }}-{{ arch }}
```
Expected result:
```
$ eval $(projectctl env)
$ my-software --version
1.2.3
```
