### ISSUE TITLE
`use`: handle custom archive

### ISSUE THREAD

**Issue by leroyguillaume** [leroyguillaume/projectctl#37]
Handle custom archve in `use` configuration entry.

Example:
```yaml
use:
  my-software:
    version: 1.2.3
    archive-url: https://my-software.com/{{ version }}/my-software-{{ version }}-{{ os }}-{{ arch }}.tar.gz
    extract: [bin/my-software-{{ version }}-{{ os }}-{{ arch }}]
```
Expected result:
```
$ eval $(projectctl env)
$ my-software --version
1.2.3
```
